robot_type: OpenArm-Bimanual
default_task: OpenDoor
task_description: pick the exhaust pipe with the left arm
features:
  observation.images.top:
    dtype: video
    shape: [256, 256, 3]
    names: ["height", "width", "channel"]
    video_info:
      video.fps: 30.0
      video.codec: h264
      video.pix_fmt: yuv420p
      video.is_depth_map: false
      has_audio: false
  observation.images.left_wrist:
    dtype: video
    shape: [256, 256, 3]
    names: ["height", "width", "channel"]
    video_info:
      video.fps: 30.0
      video.codec: h264
      video.pix_fmt: yuv420p
      video.is_depth_map: false
      has_audio: false
  observation.images.right_wrist:
    dtype: video
    shape: [256, 256, 3]
    names: ["height", "width", "channel"]
    video_info:
      video.fps: 30.0
      video.codec: h264
      video.pix_fmt: yuv420p
      video.is_depth_map: false
      has_audio: false
  observation.state:
    dtype: float32
    shape: (23,)
    names:
      - left_px
      - left_py
      - left_pz
      - left_qw
      - left_qx
      - left_qy
      - left_qz
      - left_gripper
      - right_px
      - right_py
      - right_pz
      - right_qw
      - right_qx
      - right_qy
      - right_qz
      - right_gripper
      - obj_px
      - obj_py
      - obj_pz
      - obj_qw
      - obj_qx
      - obj_qy
      - obj_qz
  action:
    dtype: float32
    shape: (14,)
    names:
      - left_x
      - left_y
      - left_z
      - left_roll
      - left_pitch
      - left_yaw
      - left_gripper
      - right_x
      - right_y
      - right_z
      - right_roll
      - right_pitch
      - right_yaw
      - right_gripper
  episode_index:
    dtype: int64
    shape: [1]
    names: null
  frame_index:
    dtype: int64
    shape: [1]
    names: null
  index:
    dtype: int64
    shape: [1]
    names: null
  task_index:
    dtype: int64
    shape: [1]
    names: null
